apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: n8n
      role: main
  template:
    metadata:
      labels:
        app: n8n
        role: main
    spec:
      containers:
        - name: n8n-main
          image: docker.n8n.io/n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: N8N_EXECUTION_MODE
              value: main
            - name: N8N_HOST
              value: "https://nxn.ggidx.click"
            - name: QUEUE_TYPE
              value: redis
            - name: REDIS_SENTINELS
              value: "n8n-redis.n8n-redis.svc.cluster.local:26379" 
            - name: REDIS_MASTER_NAME
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-redis-password
                  key: redis-password
            - name: N8N_QUEUE_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-redis-password
                  key: redis-password
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_HOST
              value: n8n-db-rw.n8n-db.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-db-secret
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-db-secret
                  key: password
            - name: DB_POSTGRESDB_SCHEMA
              value: public
            - name: GENERIC_TIMEZONE
              value: Europe/Stockholm
            - name: TZ
              value: Europe/Stockholm
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-encryption
                  key: key
            - name: N8N_PORT
              value: "5678"
            - name: N8N_DEFAULT_EDITION
              value: "community"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_LOG_LEVEL
              value: debug
          volumeMounts:
            - mountPath: "/home/node/.n8n"
              name: n8n-pv-storage

      volumes:
        - name: n8n-pv-storage
          persistentVolumeClaim:
            claimName: n8n-pvc